name: nextstory_example
description: Demonstrates how to use the nextstory plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  nextstory:
    path: ../

  provider: ^6.0.2
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
