name: nextstory_example
description: Demonstrates how to use the nextstory plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  nextstory:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
