name: nextstory
description: A Library plugin project.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  visibility_detector: any
  extended_image: ^8.2.0
  flutter_svg: ^2.0.9
  lzma: ^1.0.1

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nextstory.nextstory
        pluginClass: NextstoryPlugin
      ios:
        pluginClass: NextstoryPlugin
